stages:
  - Webapp lint
  - Webapp test
  - Backend test

Yarn Build:
  image: node:18.0.0
  stage: Webapp lint
  needs: []
  script:
    - cd dashboard
    - cd frontend
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1

Eslint:
  image: node:18.0.0
  stage: Webapp lint
  needs: [ Yarn Build ]
  script:
    - cd dashboard
    - cd frontend
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint
  retry: 1

Yarn Test:
  image: node:18.0.0
  stage: Webapp test
  needs: [ ]
  script:
    - cd dashboard
    - cd frontend
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn test
  retry: 1


UnitTest:
  image: python:3.9
  stage: Backend test
  before_script:
    - pip install -r requirements.txt
    - cd dashboard
    - python manage.py runserver 8000 &
  script:
    - python manage.py test
  retry: 1
