# Generated by Django 4.1.7 on 2023-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_user_full_name', models.CharField(max_length=100)),
                ('primary_user_email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=100)),
                ('application_name', models.CharField(max_length=100)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('family_version', models.CharField(blank=True, max_length=100, null=True)),
                ('family_edition', models.CharField(blank=True, max_length=100, null=True)),
                ('computer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_user_full_name', models.CharField(max_length=100)),
                ('primary_user_email', models.EmailField(max_length=254)),
                ('computer_name', models.CharField(max_length=100)),
                ('contact_organization', models.CharField(max_length=100)),
                ('application_name', models.CharField(max_length=100)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('family_version', models.CharField(blank=True, max_length=100, null=True)),
                ('family_edition', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.CharField(max_length=100)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='softwarepercomputer',
            name='license_suite_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
